/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YsD5WqQkt68
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Porto() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-background text-foreground">
      <header className="px-4 py-6 md:px-8 md:py-8 border-b">
        <div className="container max-w-5xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <img src="/placeholder.svg" alt="Profile Picture" width={48} height={48} className="rounded-full" />
            <div>
              <h1 className="text-xl font-bold">John Doe</h1>
              <p className="text-sm text-muted-foreground">Web Developer</p>
            </div>
          </div>
          <nav className="flex items-center gap-4">
            <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
              <GithubIcon className="w-5 h-5" />
            </Link>
            <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
              <LinkedinIcon className="w-5 h-5" />
            </Link>
            <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
              <TwitterIcon className="w-5 h-5" />
            </Link>
          </nav>
        </div>
      </header>
      <main className="flex-1 container max-w-5xl mx-auto px-4 py-12 md:px-8 md:py-16 grid gap-12">
        <section>
          <h2 className="text-2xl font-bold mb-4">About Me</h2>
          <div className="grid md:grid-cols-2 gap-8">
            <div className="prose">
              <p>
                Bonjour, je suis John Doe, un développeur web passionné. Avec une expérience de plusieurs années dans le
                domaine, j'ai acquis des compétences solides en conception, développement et déploiement d'applications
                web modernes et performantes.
              </p>
              <p>
                Mon objectif est de créer des solutions sur mesure qui répondent aux besoins spécifiques de mes clients.
                Je m'efforce toujours d'apporter une valeur ajoutée à travers mon travail et de contribuer au succès de
                leurs projets.
              </p>
            </div>
            <div className="flex justify-center">
              <img src="/placeholder.svg" alt="Profile Picture" width={300} height={300} className="rounded-lg" />
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Projects</h2>
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            <Card>
              <img
                src="/placeholder.svg"
                alt="Project 1"
                width={400}
                height={225}
                className="rounded-t-lg object-cover"
              />
              <CardContent className="p-4">
                <h3 className="text-lg font-bold mb-2">Project 1</h3>
                <p className="text-muted-foreground mb-4">
                  Description détaillée du projet 1, incluant les technologies utilisées, les fonctionnalités clés et
                  les défis relevés.
                </p>
                <div className="flex gap-2">
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Voir le site
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
                    prefetch={false}
                  >
                    Voir le code
                  </Link>
                </div>
              </CardContent>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                alt="Project 2"
                width={400}
                height={225}
                className="rounded-t-lg object-cover"
              />
              <CardContent className="p-4">
                <h3 className="text-lg font-bold mb-2">Project 2</h3>
                <p className="text-muted-foreground mb-4">
                  Description détaillée du projet 2, incluant les technologies utilisées, les fonctionnalités clés et
                  les défis relevés.
                </p>
                <div className="flex gap-2">
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Voir le site
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
                    prefetch={false}
                  >
                    Voir le code
                  </Link>
                </div>
              </CardContent>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                alt="Project 3"
                width={400}
                height={225}
                className="rounded-t-lg object-cover"
              />
              <CardContent className="p-4">
                <h3 className="text-lg font-bold mb-2">Project 3</h3>
                <p className="text-muted-foreground mb-4">
                  Description détaillée du projet 3, incluant les technologies utilisées, les fonctionnalités clés et
                  les défis relevés.
                </p>
                <div className="flex gap-2">
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Voir le site
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
                    prefetch={false}
                  >
                    Voir le code
                  </Link>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Skills</h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
            <div className="bg-muted rounded-md p-4 flex flex-col items-center">
              <HashIcon className="w-8 h-8 mb-2" />
              <span>HTML</span>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col items-center">
              <CodepenIcon className="w-8 h-8 mb-2" />
              <span>CSS</span>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col items-center">
              <CodepenIcon className="w-8 h-8 mb-2" />
              <span>JavaScript</span>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col items-center">
              <CodepenIcon className="w-8 h-8 mb-2" />
              <span>React</span>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col items-center">
              <NetworkIcon className="w-8 h-8 mb-2" />
              <span>Node.js</span>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col items-center">
              <WindIcon className="w-8 h-8 mb-2" />
              <span>Tailwind CSS</span>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col items-center">
              <GitGraphIcon className="w-8 h-8 mb-2" />
              <span>Git</span>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col items-center">
              <FigmaIcon className="w-8 h-8 mb-2" />
              <span>Figma</span>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col items-center">
              <FastForwardIcon className="w-8 h-8 mb-2" />
              <span>Next.js</span>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col items-center">
              <CloudIcon className="w-8 h-8 mb-2" />
              <span>AWS</span>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col items-center">
              <TypeIcon className="w-8 h-8 mb-2" />
              <span>TypeScript</span>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col items-center">
              <ScanIcon className="w-8 h-8 mb-2" />
              <span>Scrum</span>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Contact</h2>
          <form className="max-w-md mx-auto">
            <div className="grid gap-4">
              <div>
                <Label htmlFor="name">Nom</Label>
                <Input type="text" id="name" placeholder="Votre nom" />
              </div>
              <div>
                <Label htmlFor="email">Email</Label>
                <Input type="email" id="email" placeholder="Votre email" />
              </div>
              <div>
                <Label htmlFor="message">Message</Label>
                <Textarea id="message" placeholder="Votre message" rows={5} />
              </div>
              <Button type="submit" className="w-full">
                Envoyer
              </Button>
            </div>
          </form>
        </section>
      </main>
      <footer className="bg-muted py-6 border-t">
        <div className="container max-w-5xl mx-auto px-4 md:px-8 flex items-center justify-between">
          <p className="text-sm text-muted-foreground">&copy; 2024 John Doe. Tous droits réservés.</p>
          <nav className="flex items-center gap-4">
            <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
              Mentions légales
            </Link>
            <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
              Politique de confidentialité
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function CloudIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  )
}


function CodepenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
      <line x1="12" x2="12" y1="22" y2="15.5" />
      <polyline points="22 8.5 12 15.5 2 8.5" />
      <polyline points="2 15.5 12 8.5 22 15.5" />
      <line x1="12" x2="12" y1="2" y2="8.5" />
    </svg>
  )
}


function FastForwardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="13 19 22 12 13 5 13 19" />
      <polygon points="2 19 11 12 2 5 2 19" />
    </svg>
  )
}


function FigmaIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 5.5A3.5 3.5 0 0 1 8.5 2H12v7H8.5A3.5 3.5 0 0 1 5 5.5z" />
      <path d="M12 2h3.5a3.5 3.5 0 1 1 0 7H12V2z" />
      <path d="M12 12.5a3.5 3.5 0 1 1 7 0 3.5 3.5 0 1 1-7 0z" />
      <path d="M5 19.5A3.5 3.5 0 0 1 8.5 16H12v3.5a3.5 3.5 0 1 1-7 0z" />
      <path d="M5 12.5A3.5 3.5 0 0 1 8.5 9H12v7H8.5A3.5 3.5 0 0 1 5 12.5z" />
    </svg>
  )
}


function GitGraphIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="5" cy="6" r="3" />
      <path d="M5 9v6" />
      <circle cx="5" cy="18" r="3" />
      <path d="M12 3v18" />
      <circle cx="19" cy="6" r="3" />
      <path d="M16 15.7A9 9 0 0 0 19 9" />
    </svg>
  )
}


function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function HashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="9" y2="9" />
      <line x1="4" x2="20" y1="15" y2="15" />
      <line x1="10" x2="8" y1="3" y2="21" />
      <line x1="16" x2="14" y1="3" y2="21" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function NetworkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="16" y="16" width="6" height="6" rx="1" />
      <rect x="2" y="16" width="6" height="6" rx="1" />
      <rect x="9" y="2" width="6" height="6" rx="1" />
      <path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" />
      <path d="M12 12V8" />
    </svg>
  )
}


function ScanIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 7V5a2 2 0 0 1 2-2h2" />
      <path d="M17 3h2a2 2 0 0 1 2 2v2" />
      <path d="M21 17v2a2 2 0 0 1-2 2h-2" />
      <path d="M7 21H5a2 2 0 0 1-2-2v-2" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function TypeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="4 7 4 4 20 4 20 7" />
      <line x1="9" x2="15" y1="20" y2="20" />
      <line x1="12" x2="12" y1="4" y2="20" />
    </svg>
  )
}


function WindIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.7 7.7a2.5 2.5 0 1 1 1.8 4.3H2" />
      <path d="M9.6 4.6A2 2 0 1 1 11 8H2" />
      <path d="M12.6 19.4A2 2 0 1 0 14 16H2" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
